jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: 使用 Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Checkout 代码
      uses: actions/checkout@v2
      
    - name: 更新 README
      run: |
        current_time=$(date "+%Y-%m-%d %H:%M:%S")
        echo "最后更新时间：$current_time" >> readme.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add readme.md
        git commit -m "自动更新 README"
        git push
